IniReader.hpp: include cstdint
/usr/bin/powerpc64le-unknown-linux-musl-g++ -DDOCDIR=\"/usr//usr/share/doc/openrct2-0.5.5\" -DUSE_MMAP -D_FILE_OFFSET_BITS=64 -D__WARN_SUGGEST_FINAL_METHODS__ -D__WARN_SUGGEST_FINAL_TYPES__ -Dlibopenrct2_EXPORTS -I/var/tmp/portage/games-simulation/openrct2-0.5.5/work/OpenRCT2-0.5.5/libopenrct2 -isystem /usr/include/freetype2 -isystem /usr/include/libpng16 -isystem /var/tmp/portage/games-simulation/openrct2-0.5.5/work/OpenRCT2-0.5.5/src/openrct2/../thirdparty  -O2 -pipe -mcpu=power9 -fgraphite-identity -floop-nest-optimize -ftrivial-auto-var-init=zero -flto=auto -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing -fno-semantic-interposition -fstrict-overflow -fstrict-aliasing  -Wundef -Wmissing-declarations -Winit-self -Wall -Wextra -Wshadow -Wno-unknown-pragmas -Wno-missing-braces -Wno-comment -Wnonnull -Wno-unused-parameter -Wno-attributes -DDEBUG=0 -fno-char8_t -Wno-deprecated-declarations -std=gnu++20 -fPIC -Wsuggest-override -Wduplicated-cond -Wnon-virtual-dtor -Wduplicated-branches -Wrestrict -Wmissing-field-initializers -Wlogical-op -Wold-style-cast -Wunused-const-variable=1 -Wno-clobbered -Wredundant-decls -Wnull-dereference -Wsuggest-final-types -Wsuggest-final-methods -Wignored-qualifiers -Wstrict-overflow=1 -MD -MT CMakeFiles/libopenrct2.dir/src/openrct2/config/IniReader.cpp.o -MF CMakeFiles/libopenrct2.dir/src/openrct2/config/IniReader.cpp.o.d -o CMakeFiles/libopenrct2.dir/src/openrct2/config/IniReader.cpp.o -c /var/tmp/portage/games-simulation/openrct2-0.5.5/work/OpenRCT2-0.5.5/src/openrct2/config/IniReader.cpp
In file included from /var/tmp/portage/games-simulation/openrct2-0.5.5/work/OpenRCT2-0.5.5/src/openrct2/config/IniReader.cpp:10:
/var/tmp/portage/games-simulation/openrct2-0.5.5/work/OpenRCT2-0.5.5/src/openrct2/config/IniReader.hpp:31:13: error: 'int32_t' does not name a type
   31 |     virtual int32_t GetInt32(const std::string& name, int32_t defaultValue) const = 0;
      |             ^~~~~~~
/var/tmp/portage/games-simulation/openrct2-0.5.5/work/OpenRCT2-0.5.5/src/openrct2/config/IniReader.hpp:14:1: note: 'int32_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
   13 | #include <memory>
  +++ |+#include <cstdint>
   14 | #include <string>
/var/tmp/portage/games-simulation/openrct2-0.5.5/work/OpenRCT2-0.5.5/src/openrct2/config/IniReader.hpp:32:13: error: 'int64_t' does not name a type
   32 |     virtual int64_t GetInt64(const std::string& name, int64_t defaultValue) const = 0;
      |             ^~~~~~~
/var/tmp/portage/games-simulation/openrct2-0.5.5/work/OpenRCT2-0.5.5/src/openrct2/config/IniReader.hpp:32:13: note: 'int64_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
/var/tmp/portage/games-simulation/openrct2-0.5.5/work/OpenRCT2-0.5.5/src/openrct2/config/IniReader.cpp:141:13: error: 'int32_t IniReader::GetInt32(const std::string&, int32_t) const' marked 'override', but does not override
  141 |     int32_t GetInt32(const std::string& name, int32_t defaultValue) const override
      |             ^~~~~~~~
/var/tmp/portage/games-simulation/openrct2-0.5.5/work/OpenRCT2-0.5.5/src/openrct2/config/IniReader.cpp:158:13: error: 'int64_t IniReader::GetInt64(const std::string&, int64_t) const' marked 'override', but does not override
  158 |     int64_t GetInt64(const std::string& name, int64_t defaultValue) const override
      |             ^~~~~~~~
/var/tmp/portage/games-simulation/openrct2-0.5.5/work/OpenRCT2-0.5.5/src/openrct2/config/IniReader.cpp:404:13: error: 'int32_t DefaultIniReader::GetInt32(const std::string&, int32_t) const' marked 'override', but does not override
  404 |     int32_t GetInt32([[maybe_unused]] const std::string& name, int32_t defaultValue) const override
      |             ^~~~~~~~
/var/tmp/portage/games-simulation/openrct2-0.5.5/work/OpenRCT2-0.5.5/src/openrct2/config/IniReader.cpp:409:13: error: 'int64_t DefaultIniReader::GetInt64(const std::string&, int64_t) const' marked 'override', but does not override
  409 |     int64_t GetInt64([[maybe_unused]] const std::string& name, int64_t defaultValue) const override
      |             ^~~~~~~~