MapChangeSizeAction+EditorStepController: properly guard scripting (#27139)
/usr/bin/powerpc64le-unknown-linux-musl-g++ -DDOCDIR=\"/usr//usr/share/doc/openrct2-0.5.5\" -DOPENGL_NO_LINK -DUSE_MMAP -D_FILE_OFFSET_BITS=64 -D__WARN_SUGGEST_FINAL_METHODS__ -D__WARN_SUGGEST_FINAL_TYPES__ -I/var/tmp/portage/games-simulation/openrct2-0.5.5/work/OpenRCT2-0.5.5/libopenrct2 -I/var/tmp/portage/games-simulation/openrct2-0.5.5/work/OpenRCT2-0.5.5/src/openrct2-ui/.. -isystem /var/tmp/portage/games-simulation/openrct2-0.5.5/work/OpenRCT2-0.5.5/src/openrct2/../thirdparty -isystem /usr/include/SDL2 -isystem /var/tmp/portage/games-simulation/openrct2-0.5.5/work/OpenRCT2-0.5.5/src/openrct2-ui/../thirdparty -isystem /usr/include/libpng16 -isystem /usr/include/freetype2  -O2 -pipe -mcpu=power9 -fgraphite-identity -floop-nest-optimize -ftrivial-auto-var-init=zero -flto=auto -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing -fno-semantic-interposition -fstrict-overflow -fstrict-aliasing  -Wundef -Wmissing-declarations -Winit-self -Wall -Wextra -Wshadow -Wno-unknown-pragmas -Wno-missing-braces -Wno-comment -Wnonnull -Wno-unused-parameter -Wno-attributes -DDEBUG=0 -fno-char8_t -Wno-deprecated-declarations -std=gnu++20 -fPIE -Wsuggest-override -Wduplicated-cond -Wnon-virtual-dtor -Wduplicated-branches -Wrestrict -Wmissing-field-initializers -Wlogical-op -Wold-style-cast -Wunused-const-variable=1 -Wno-clobbered -Wredundant-decls -Wnull-dereference -Wsuggest-final-types -Wsuggest-final-methods -Wignored-qualifiers -Wstrict-overflow=1 -D_REENTRANT -MD -MT CMakeFiles/openrct2.dir/src/openrct2-ui/windows/EditorStepController.cpp.o -MF CMakeFiles/openrct2.dir/src/openrct2-ui/windows/EditorStepController.cpp.o.d -o CMakeFiles/openrct2.dir/src/openrct2-ui/windows/EditorStepController.cpp.o -c /var/tmp/portage/games-simulation/openrct2-0.5.5/work/OpenRCT2-0.5.5/src/openrct2-ui/windows/EditorStepController.cpp
/var/tmp/portage/games-simulation/openrct2-0.5.5/work/OpenRCT2-0.5.5/src/openrct2-ui/windows/EditorStepController.cpp: In member function 'void OpenRCT2::Ui::Windows::EditorStepController::drawButtonCaption(OpenRCT2::Drawing::RenderTarget&)':
/var/tmp/portage/games-simulation/openrct2-0.5.5/work/OpenRCT2-0.5.5/src/openrct2-ui/windows/EditorStepController.cpp:339:28: error: 'STR_EDITOR_STEP_OBJECT_SELECTION' was not declared in this scope
  339 |                 stringId = STR_EDITOR_STEP_OBJECT_SELECTION;
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/games-simulation/openrct2-0.5.5/work/OpenRCT2-0.5.5/src/openrct2-ui/windows/EditorStepController.cpp:341:28: error: 'STR_EDITOR_STEP_ROLLERCOASTER_DESIGNER' was not declared in this scope; did you mean 'STR_QUIT_ROLLERCOASTER_DESIGNER'?
  341 |                 stringId = STR_EDITOR_STEP_ROLLERCOASTER_DESIGNER;
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                            STR_QUIT_ROLLERCOASTER_DESIGNER
ninja: build stopped: subcommand failed.