UiContext.h: add missing cstdint
/usr/bin/powerpc64le-unknown-linux-musl-g++ -DDOCDIR=\"/usr//usr/share/doc/openrct2-0.5.5\" -DOPENGL_NO_LINK -DUSE_MMAP -D_FILE_OFFSET_BITS=64 -D__WARN_SUGGEST_FINAL_METHODS__ -D__WARN_SUGGEST_FINAL_TYPES__ -I/var/tmp/portage/games-simulation/openrct2-0.5.5/work/OpenRCT2-0.5.5/libopenrct2 -I/var/tmp/portage/games-simulation/openrct2-0.5.5/work/OpenRCT2-0.5.5/src/openrct2-ui/.. -isystem /var/tmp/portage/games-simulation/openrct2-0.5.5/work/OpenRCT2-0.5.5/src/openrct2/../thirdparty -isystem /usr/include/SDL2 -isystem /var/tmp/portage/games-simulation/openrct2-0.5.5/work/OpenRCT2-0.5.5/src/openrct2-ui/../thirdparty -isystem /usr/include/libpng16 -isystem /usr/include/freetype2  -O2 -pipe -mcpu=power9 -fgraphite-identity -floop-nest-optimize -ftrivial-auto-var-init=zero -flto=auto -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing -fno-semantic-interposition -fstrict-overflow -fstrict-aliasing  -Wundef -Wmissing-declarations -Winit-self -Wall -Wextra -Wshadow -Wno-unknown-pragmas -Wno-missing-braces -Wno-comment -Wnonnull -Wno-unused-parameter -Wno-attributes -DDEBUG=0 -fno-char8_t -Wno-deprecated-declarations -std=gnu++20 -fPIE -Wsuggest-override -Wduplicated-cond -Wnon-virtual-dtor -Wduplicated-branches -Wrestrict -Wmissing-field-initializers -Wlogical-op -Wold-style-cast -Wunused-const-variable=1 -Wno-clobbered -Wredundant-decls -Wnull-dereference -Wsuggest-final-types -Wsuggest-final-methods -Wignored-qualifiers -Wstrict-overflow=1 -D_REENTRANT -MD -MT CMakeFiles/openrct2.dir/src/openrct2-ui/windows/Scenery.cpp.o -MF CMakeFiles/openrct2.dir/src/openrct2-ui/windows/Scenery.cpp.o.d -o CMakeFiles/openrct2.dir/src/openrct2-ui/windows/Scenery.cpp.o -c /var/tmp/portage/games-simulation/openrct2-0.5.5/work/OpenRCT2-0.5.5/src/openrct2-ui/windows/Scenery.cpp
In file included from /var/tmp/portage/games-simulation/openrct2-0.5.5/work/OpenRCT2-0.5.5/src/openrct2-ui/windows/Scenery.cpp:11:
/var/tmp/portage/games-simulation/openrct2-0.5.5/work/OpenRCT2-0.5.5/src/openrct2-ui/../openrct2-ui/UiContext.h:41:17: error: 'int32_t' does not name a type
   41 |         virtual int32_t ShowMenuDialog(
      |                 ^~~~~~~
/var/tmp/portage/games-simulation/openrct2-0.5.5/work/OpenRCT2-0.5.5/src/openrct2-ui/../openrct2-ui/UiContext.h:16:1: note: 'int32_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
   15 | #include <vector>
  +++ |+#include <cstdint>
   16 |